# Generated by Django 3.2.7 on 2021-09-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210911_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
