# Generated by Django 3.2.7 on 2021-10-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_listings_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='house_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='house_image2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='house_image3',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='house_image4',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='house_image5',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
